participants:
  - el_client_type: geth
    cl_client_type: prysm
    count: 1
  - el_client_type: geth
    cl_client_type: prysm
    count: 1
  - el_client_type: geth
    cl_client_type: prysm
    count: 1
additional_services: []
disable_peer_scoring: true
